### ISSUE TITLE
[Feature] El Flow de registro necesita ser simple

### ISSUE THREAD

**Issue by bpallares** [eveforo/discourse-oauth2-basic#3]
@juvenius  Define

**Comment by juvenius** [comment]
la idea es que NO SE PUEDA REGISTRAR con el correo unicamente.....mi idea es..

Login con el SSO DE EVE >>> then Pide correo >> then valida correo >> then OK eres miembro enseguida sin necesidad de autorizacion.

**Comment by bpallares** [comment]
Perfecto

**Comment by bpallares** [comment]
@juvenius  Desactivando las siguientes opciones desactiva el login y registro por mail.

<img width="841" alt="Screen Shot 2019-10-12 at 2 38 01 AM" src="https://user-images.githubusercontent.com/17114134/66697239-6fb82000-ec99-11e9-9c69-36b56ea54e8d.png">

Sin embargo, el plugin aun da la libertad de cambiar el nickname o login despues de la authorizacion

<img width="512" alt="Screen Shot 2019-10-12 at 2 37 32 AM" src="https://user-images.githubusercontent.com/17114134/66697272-aaba5380-ec99-11e9-970d-a28a72144273.png">
